# Generated by Django 2.2.6 on 2019-11-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_auto_20191123_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
